"""
This is the place I store all my helper functions for the LikelihoodShape project
the name N_Tools is patterned after MF_Tools
"""

import re
from typing import Callable
import numpy as np
from manim import *
from MF_Tools import *

#Some useful helper methods
def as_row(vec):
    return vec.reshape(1,-1)
def as_col(vec):
    return vec.reshape(-1,1)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def round_sig(x, sig=4):
    x = np.asarray(x)
    
    # Handle zeros separately to avoid log10 issues
    zero_mask = (x == 0)
    
    # Compute scale factor
    mags = np.floor(np.log10(np.abs(x)), where=~zero_mask, out=np.zeros_like(x))
    factor = np.power(10, sig - 1 - mags)
    
    # Round and rescale
    result = np.round(x * factor) / factor
    
    # Restore zeros
    result[zero_mask] = 0
    return result

def simple_linear_regression(X, Y):
    X = np.asarray(X)
    Y = np.asarray(Y)
    
    if X.shape != Y.shape:
        raise ValueError("X and Y must have the same shape")
    
    x_mean = X.mean()
    y_mean = Y.mean()
    
    # slope (beta_1)
    beta_1 = np.sum((X - x_mean) * (Y - y_mean)) / np.sum((X - x_mean)**2)
    
    # intercept (beta_0)
    beta_0 = y_mean - beta_1 * x_mean
    
    return beta_0, beta_1

import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Generated by AI, I hope this is right
def logistic_regression(X, y, max_iter=100, tol=1e-6, add_intercept = False, return_stats = False):
    """
    Fits logistic regression using Newton-Raphson (IRLS).

    Parameters:
        X : (n, p) design matrix (include column of 1s if you want intercept)
        y : (n,) binary response (0 or 1)
        max_iter : maximum number of iterations
        tol : convergence tolerance

    Returns:
        beta : (p,) estimated coefficients
    """

    n, p = X.shape

    if add_intercept:
        X = np.c_[np.ones(n), X]
        n, p = X.shape

    beta = np.zeros(p)


    for _ in range(max_iter):
        z = X @ beta
        p_hat = sigmoid(z)

        # Gradient: X^T (y - p)
        grad = X.T @ (y - p_hat)

        # Hessian: -X^T W X where W = diag(p(1-p))
        W = p_hat * (1 - p_hat)
        # Avoid forming full diagonal matrix
        X_weighted = X * W[:, np.newaxis]
        hessian = -(X.T @ X_weighted)

        # Newton step
        try:
            delta = np.linalg.solve(hessian, grad)
        except np.linalg.LinAlgError:
            # fallback if singular
            delta = np.linalg.pinv(hessian) @ grad

        beta_new = beta - delta

        # Convergence check
        if np.linalg.norm(beta_new - beta) < tol:
            beta = beta_new
            break

        beta = beta_new

    if not return_stats:
        return beta

    # --- Compute covariance matrix at optimum ---
    z = X @ beta
    p_hat = sigmoid(z)
    W = p_hat * (1 - p_hat)

    X_weighted = X * W[:, np.newaxis]
    fisher_info = X.T @ X_weighted  # = X^T W X

    try:
        cov = np.linalg.inv(fisher_info)
    except np.linalg.LinAlgError:
        cov = np.linalg.pinv(fisher_info)

    se = np.sqrt(np.diag(cov))

    return beta, cov, se

def log_likelihood(X, y, beta, add_intercept = False):
    n, p = X.shape

    if add_intercept:
        X = np.c_[np.ones(n), X]
    z = X @ beta
    return np.sum(y * z - np.logaddexp(0, z))

# Turns a numpy tensor into TeX which is nice for displaying.
# Generated by ChatGPT, modified by Noah
def numpy_to_latex(
    arr: np.ndarray,
    sigfigs: int = 4,
    max_rows: int = -1, # -1 automatically calculates
    max_cols: int = -1, # -1 automatically calculates
    tail_rows: int = 2,
    tail_cols: int = 2,
    make_table: bool = False,
    colnames: list[str] = []
) -> str:
    if not isinstance(arr, np.ndarray):
        raise TypeError("Input must be a numpy.ndarray")

    if arr.ndim >= 3:
        raise ValueError("Array must be 1D or 2D")

    # Treat 1D arrays as column vectors
    if arr.ndim == 1:
        arr = as_col(arr)

    n_rows, n_cols = arr.shape
    
    # If automatically calculating max_rows or max_cols, do so here
    def display_size(
        n,
        full_threshold=8,
        max_display=14,
        scale=0.03):
        if n <= full_threshold:
            return n
        return min(max_display, int(full_threshold + scale * (n - full_threshold)))
    
    if max_rows == -1:
        max_rows = display_size(n_rows)
    if max_cols == -1:
        max_cols = display_size(n_cols)

    if tail_rows < 0 or tail_cols < 0:
        raise ValueError("tail_rows and tail_cols must be nonnegative")

    def format_entry(x):
        try:
            x = float(x)
            return f"{x:.{sigfigs}g}"
        except (ValueError, TypeError):
            return str(x)

    def indices(n, max_n, tail_n):
        if n <= max_n:
            return list(range(n)), False

        if tail_n + 1 >= max_n:
            raise ValueError("tail_n is too large relative to max_n")

        head_n = max_n - tail_n - 1
        idx = list(range(head_n)) + list(range(n - tail_n, n))
        return idx, True

    row_idx, row_trunc = indices(n_rows, max_rows, tail_rows)
    col_idx, col_trunc = indices(n_cols, max_cols, tail_cols)

    if colnames:
        rows = [" & ".join(colnames) + "\n"]
    else:
        rows = []

    for i in row_idx:
        entries = []
        for j in col_idx:
            entries.append(format_entry(arr[i, j]))

        if col_trunc:
            # Insert horizontal ellipsis before the tail columns
            insert_at = len(entries) - tail_cols
            entries.insert(insert_at, r"\ldots")

        rows.append(" & ".join(entries))

    if row_trunc:
        ellipsis_row = []
        displayed_cols = len(col_idx) + (1 if col_trunc else 0)
        if make_table:
            ellipsis_row = [r"$\vdots$"] * displayed_cols
        else:
            ellipsis_row = [r"\vdots"] * displayed_cols

        if col_trunc:
            ellipsis_col = len(ellipsis_row) - tail_cols - 1
            ellipsis_row[ellipsis_col] = r"$\ddots$" if make_table else r"\ddots" 

        # Insert ellipsis row before the tail rows
        insert_at = len(rows) - tail_rows
        rows.insert(insert_at, " & ".join(ellipsis_row))

    if make_table:
        body = " \\\\\n\\hline\n    ".join(rows)
        body = f"\\hline\n{body} \\\\\n\\hline\n"
    else:
        body = " \\\\\n    ".join(rows)

    # Check that every column has the same number of "&" because otherwise LaTeX will complain
    if True:
        expected_cols = None
        for r in rows:
            count = r.count("&")
            if expected_cols is None:
                expected_cols = count
            elif count != expected_cols:
                raise RuntimeError("Inconsistent column count in LaTeX matrix")

    
    if make_table:
        header_text = "|" + " c |" * max_cols
        return (
            f"\\begin{{tabular}}{{ {header_text} }}\n"
            f"    {body}\n"
            "\\end{tabular}"
        )
    else:
        return (
            "\\begin{bmatrix}\n"
            f"    {body}\n"
            "\\end{bmatrix}"
        )
    
def latex_table_to_array(latex_str):
    # Remove common LaTeX table wrappers
    latex_str = re.sub(r"\\begin\{.*?\}|\\end\{.*?\}", "", latex_str)
    latex_str = latex_str.replace(r"\hline", "")
    latex_str = latex_str.replace("$", "")

    # print(f"{latex_str=}")
    
    # Split into rows
    rows = re.split(r"\\\\", latex_str)

    # print(f"{rows=}")

    table = []
    
    for row in rows:
        row = row.strip()
        
        # Skip empty lines and \hline rows
        if not row:
            continue
        
        # Split into cells
        cells = row.split("&")

        # print(f"{cells=}")
        
        parsed_row = []
        for cell in cells:
            cell = cell.strip()
                        
            # Try to parse float
            try:
                val = float(cell)
            except ValueError: # Can't be parsed as a float
                val = np.nan
            
            parsed_row.append(val)
        
        table.append(parsed_row)
    
    return np.array(table, dtype=np.float64)

def square_matrix_tex(n : int, 
                      generator: Callable[[int, int], str],
                      start_ij: int = 1):
    rows = []
    for i in range(start_ij, n + start_ij):
        row = []
        for j in range(start_ij, n + start_ij):
            entry = generator(i, j)
            row.append(entry)
        rows.append(" & ".join(row))
    
    matrix_body = " \\\\\n".join(rows)
    
    latex = (
        "\\begin{bmatrix}\n"
        f"{matrix_body}\n"
        "\\end{bmatrix}\n"
    )
    return latex

def latex_vector(elements, orientation="column", bracket="bmatrix"):
    """
    Convert a list of strings into a LaTeX vector.

    Parameters:
        elements (list of str): The entries of the vector.
        orientation (str): "column" or "row".
        bracket (str): LaTeX matrix environment (e.g., "pmatrix", "bmatrix", "vmatrix").

    Returns:
        str: LaTeX string representing the vector.
    """
    if not elements:
        raise ValueError("elements list cannot be empty")

    if orientation == "col":
        orientation = "column"

    if orientation not in {"column", "row"}:
        raise ValueError("orientation must be 'column' or 'row'")

    if orientation == "column":
        body = " \\\\ ".join(elements)
    else:  # row
        body = " & ".join(elements)

    return f"\\begin{{{bracket}}}{body}\\end{{{bracket}}}"

def create_graph(
    func,
    x_range=None,
    y_range=None,
    x_label="x",
    y_label="y",
    domain=None,
    inverse_mode=False,
    inverse_func=None,   # maps y -> x (for inverse_mode mode)
    t_range=None,        # range in output space (y-space)
    n_points=1000,
    width = None,
    height = None,
    color=RED,
):
    # ---- defaults (avoid mutable args) ----
    x_range = x_range or [-5, 5, 1]
    y_range = y_range or [-5, 5, 1]

    if len(x_range) == 2:
        x_range = [*x_range, (x_range[1] - x_range[0]) * 0.1]
    if len(y_range) == 2:
        y_range = [*y_range, (y_range[1] - y_range[0]) * 0.1]

    domain = domain or x_range[0:2]
    if len(domain) == 2:
        step_size = (domain[1] - domain[0]) / n_points
        domain = [*domain, step_size]

    # ---- axes ----

    axes = Axes(
        x_range=x_range,
        y_range=y_range,
        x_length=width if width is not None else 6,
        y_length=height if height is not None else 6,
    ).add_coordinates()
    labels = axes.get_axis_labels(x_label=x_label, y_label=y_label)
    labels = axes.get_axis_labels(x_label=x_label, y_label=y_label)

    # ---- choose plotting mode ----
    if inverse_mode:
        if inverse_func is None:
            raise ValueError("inverse_mode=True requires inverse_func (mapping y -> x)")

        # default t_range from visible y-axis
        if t_range is None:
            t_range = y_range[0:2]
            # Apparently you can't control the step_size in t_range so never mind
            # step_size = (t_range[1] - t_range[0]) / n_points
            # t_range.append(step_size)

        def parametric(t):
            x = inverse_func(t)
            return axes.c2p(x, t)

        graph = ParametricFunction(
            parametric,
            t_range=t_range,
            color=color,
        )

    else:
        graph = axes.plot(
            func,
            x_range=domain,
            color=color,
        )

    return VGroup(axes, labels, graph)

# Generated by ChatGPT
# TODO: More robust strategies for dealing with fraction bars and pipes, etc.
def extract_table_grid(tex):
    glyphs = tex[0]

    vertical_lines = []
    horizontal_lines = []
    content = []

    # --- Step 1: classify glyphs ---
    for i, g in enumerate(glyphs):
        w, h = g.width, g.height

        if h > 5 * w:  # vertical line
            vertical_lines.append((i, g))
        elif w > 5 * h:  # horizontal line
            horizontal_lines.append((i, g))
        else:
            content.append((i, g))

    # print(f"{vertical_lines=}, {horizontal_lines=}, {content=}")

    # --- Step 2: get grid boundaries ---
    # Use centers of lines
    x_lines = sorted([g.get_center()[0] for _, g in vertical_lines])
    y_lines = sorted([g.get_center()[1] for _, g in horizontal_lines], reverse=True)

    # Deduplicate (important if LaTeX draws lines in segments)
    def dedup(vals, tol=1e-2):
        out = []
        for v in vals:
            if not any(abs(v - o) < tol for o in out):
                out.append(v)
        return sorted(out)

    x_lines = dedup(x_lines)
    y_lines = dedup(y_lines)[::-1]  # top → bottom

    # --- Step 3: build cells ---
    grid = {}

    for idx, g in content:
        x, y, _z = g.get_center()

        # find column: between vertical lines
        col = None
        for j in range(len(x_lines) - 1):
            if x_lines[j] < x < x_lines[j + 1]:
                col = j
                break

        # find row: between horizontal lines
        row = None
        for i in range(len(y_lines) - 1):
            if y_lines[i] > y > y_lines[i + 1]:
                row = i
                break

        if row is not None and col is not None:
            grid.setdefault((row, col), []).append(idx)
        else:
            pass
            # print((row, col))

    return grid

# This method is deprecated, and you should use TransformMatchingCells instead
def TransformByCellMap(table1, table2, *maps):
    table1_grid = extract_table_grid(table1)
    table2_grid = extract_table_grid(table2)

    glyph_map = []
    for start, end in maps:
        start_indices = table1_grid[start] if start in table1_grid else []
        end_indices = table2_grid[end] if end in table2_grid else []
        glyph_map.append((start_indices, end_indices))
    
    return TransformByGlyphMap(table1, table2, *glyph_map)

def TransformMatchingCells(table1, table2):
    table1_grid = extract_table_grid(table1)
    table2_grid = extract_table_grid(table2)

    glyph_map = []
    maps = table1_grid.keys() | table2_grid.keys()
    for coords in maps:
        start_indices = table1_grid[coords] if coords in table1_grid else []
        end_indices = table2_grid[coords] if coords in table2_grid else []
        glyph_map.append((start_indices, end_indices))
    
    return TransformByGlyphMap(table1, table2, *glyph_map)

def highlight_row(tex, row_idx, color=RED, opacity=0.3):
    glyphs = tex[0]  # important fix

    # --- classify horizontal lines ---
    horizontal_lines = []
    for g in glyphs:
        w, h = g.width, g.height
        if w > 3 * h:  # horizontal line
            horizontal_lines.append(g)

    # --- extract and deduplicate y positions ---
    y_lines = sorted([g.get_center()[1] for g in horizontal_lines], reverse=True)

    def dedup(vals, tol=1e-2):
        out = []
        for v in vals:
            if not any(abs(v - o) < tol for o in out):
                out.append(v)
        return out

    y_lines = dedup(y_lines)

    # --- safety check ---
    if row_idx >= len(y_lines) - 1:
        raise ValueError("Row index out of range")

    y_top = y_lines[row_idx]
    y_bottom = y_lines[row_idx + 1]

    # --- compute rectangle geometry ---
    height = y_top - y_bottom
    y_center = (y_top + y_bottom) / 2

    # full table width
    left = min(g.get_left()[0] for g in glyphs)
    right = max(g.get_right()[0] for g in glyphs)
    width = right - left
    x_center = (left + right) / 2

    rect = Rectangle(width=width, height=height)
    rect.move_to([x_center, y_center, 0])
    rect.set_fill(color, opacity=opacity)
    rect.set_stroke(width=0)

    return rect